apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-error-monitor-backend
  namespace: pod-error-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-error-monitor-backend
  template:
    metadata:
      labels:
        app: pod-error-monitor-backend
    spec:
      serviceAccountName: pod-error-monitor
      containers:
      - name: backend
        image: pod-error-monitor-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /api/namespaces
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/namespaces
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: pod-error-monitor-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-error-monitor-config
  namespace: pod-error-monitor
data:
  config.yaml: |
    server:
      port: 8080
      host: "0.0.0.0"
      cors:
        allowed_origins:
          - "http://localhost:3000"
          - "http://localhost:80"
        allowed_methods:
          - "GET"
          - "POST"
          - "OPTIONS"

    kubernetes:
      use_in_cluster: true
      kubeconfig_path: "/root/.kube/config"
      default_context: ""
      refresh_interval: 5

    monitoring:
      high_restart_threshold: 5
      error_weights:
        crash_loop: 3.0
        image_pull: 2.0
        high_restarts: 2.0
        other_errors: 1.0
        restart_multiplier: 0.1
---
apiVersion: v1
kind: Service
metadata:
  name: pod-error-monitor-backend
  namespace: pod-error-monitor
spec:
  selector:
    app: pod-error-monitor-backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 