# Server configuration
server:
  port: 8080
  host: "0.0.0.0"
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:80"
    allowed_methods:
      - "GET"
      - "POST"
      - "OPTIONS"

# Kubernetes configuration
kubernetes:
  # Set to true to use in-cluster config, false to use kubeconfig
  use_in_cluster: false
  # Path to kubeconfig file (used when use_in_cluster is false)
  kubeconfig_path: "/Users/jankejr/.kube/config"
  # Default context to use (optional)
  default_context: ""
  # Refresh interval for pod status (in seconds)
  refresh_interval: 5

# Monitoring configuration
monitoring:
  # Threshold for high restart count
  high_restart_threshold: 1
  # Error scoring weights
  error_weights:
    crash_loop: 3.0
    image_pull: 2.0
    high_restarts: 2.0
    other_errors: 1.0
    restart_multiplier: 0.1 